brew "mas"
brew "ktfmt"
brew "cocoapods"
brew "swiftgen"
brew "scrcpy"
brew "gradle-profiler"
brew "mrmans0n/tap/gg-stack"
brew "lazygit"

cask "shottr"
cask "linearmouse"
cask "nikitabobko/tap/aerospace"
cask "ghostty"
cask "marta"
cask "openmtp"
cask "slack"
cask "zen"
cask "android-platform-tools"
